#!/usr/bin/env bash

install_dir="$HOME/.files"
src_dir='/tmp/.files'
repo_url='https://github.com/cadeef/.files.git'

function main() {
    if [ "$1" == "--force" -o "$1" == "-f" ]; then
        install
    else
        read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            install
        fi
    fi
}

function get_source() {

    if [ -d ${src_dir} ]; then
        cd ${src_dir} && \
        git pull origin master
    else
        git clone ${repo_url} ${src_dir}
    fi
}

function install() {
    get_source

    cd ${src_dir} || (echo "FATAL: Could change to $src_dir"; exit 5)

    for dir in {bin,bash.d,state}; do
        path="$install_dir/$dir"
        [ -d ${path} ] || mkdir -v -p ${path}
        [ -d ./${dir} ] && rsync -ah --no-perms ./${dir}/ ${path}/
    done

    rsync -ah --no-perms --exclude='bash.d' ./dots/ ${HOME}/
    cp -f ./dotfiler ${install_dir}/bin

    source ~/.bash_profile
}

main
